import type { StatusCardData, CompanyRating, WorkspaceTask, TaskDetail } from '@/types/workspace';

export const STATUS_CARDS: StatusCardData[] = [
  { tagType: 'blue', tagLabel: '지원', count: 12 },
  { tagType: 'green', tagLabel: '진행 중', count: 3 },
  { tagType: 'purple', tagLabel: '진행 완료', count: 4 },
  { tagType: 'cyan', tagLabel: '제출 완료', count: 5 },
  { tagType: 'gray', tagLabel: '정산 완료', count: 678 },
];

export const RATINGS: CompanyRating[] = [
  { category: '전체 평균', score: 4.2 },
  { category: '결과물 완성도', score: 4.0 },
  { category: '실행력', score: 3.8 },
  { category: '커뮤니케이션', score: 4.1 },
  { category: '일정 준수', score: 3.9 },
  { category: '재협업 의향', score: 4.3 },
];

export const FUNDING = {
  amount: '1,250,000',
  message: '차곡차곡 쌓이고 있어요!',
};

export const TASKS: WorkspaceTask[] = [
  {
    id: '1',
    taskType: 'selection',
    taskName: '선정 완료',
    indicatorType: 'blue',
    indicatorLabel: '확인 필요',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p1',
  },
  {
    id: '2',
    taskType: 'projectStart',
    taskName: '프로젝트 시작 예정',
    indicatorType: 'blue',
    indicatorLabel: '확인 필요',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p2',
  },
  {
    id: '3',
    taskType: 'feedback',
    taskName: '기업 피드백 대응',
    indicatorType: 'blue',
    indicatorLabel: '확인 필요',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p3',
  },
  {
    id: '4',
    taskType: 'projectEnd',
    taskName: '프로젝트 종료 예정',
    indicatorType: 'blue',
    indicatorLabel: '확인 필요',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p4',
  },
  {
    id: '5',
    taskType: 'submission',
    taskName: '결과물 제출',
    indicatorType: 'green',
    indicatorLabel: '진행 중',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p5',
  },
  {
    id: '6',
    taskType: 'approval',
    taskName: '결과 승인 완료',
    indicatorType: 'green',
    indicatorLabel: '진행 중',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p6',
  },
  {
    id: '7',
    taskType: 'settlement',
    taskName: '정산 확인 필요',
    indicatorType: 'green',
    indicatorLabel: '진행 중',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p7',
  },
  {
    id: '8',
    taskType: 'feedback',
    taskName: '기업 피드백 대응',
    indicatorType: 'gray',
    indicatorLabel: '완료',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p8',
  },
  {
    id: '9',
    taskType: 'feedback',
    taskName: '기업 피드백 대응',
    indicatorType: 'gray',
    indicatorLabel: '완료',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p9',
  },
  {
    id: '10',
    taskType: 'feedback',
    taskName: '기업 피드백 대응',
    indicatorType: 'gray',
    indicatorLabel: '완료',
    projectName: '프로젝트명',
    brandName: '브랜드명',
    registeredDate: '2000.00.00',
    projectId: 'p10',
  },
];

// === 프로젝트 현황 탭 ===

export const PROJECT_TAB_COUNTS = [
  { label: '전체', count: 12 },
  { label: '지원', count: 2 },
  { label: '진행 중', count: 1 },
  { label: '진행 완료', count: 1 },
  { label: '제출 완료', count: 1 },
  { label: '정산 완료', count: 6 },
];

const TAG_MAP: Record<string, { type: string; label: string }> = {
  지원: { type: 'blue', label: '지원' },
  진행중: { type: 'green', label: '진행 중' },
  진행완료: { type: 'purple', label: '진행 완료' },
  제출완료: { type: 'cyan', label: '제출 완료' },
  정산완료: { type: 'gray', label: '정산 완료' },
  미선정: { type: 'yellow', label: '미선정' },
};

export const PROJECT_CARDS = [
  {
    id: '1',
    status: '지원',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '2',
    status: '지원',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '3',
    status: '진행중',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '4',
    status: '진행완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '5',
    status: '제출완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '6',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '7',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '8',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '9',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '10',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '11',
    status: '정산완료',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
  {
    id: '12',
    status: '미선정',
    title: 'F&B 신제품 캠퍼스 숏폼 프로젝트',
    brand: 'Sparkle Drink',
    category1: 'F&B',
    category2: '숏폼·UGC',
    startDate: '2025.05.10',
    endDate: '2025.05.28',
  },
];

export function getProjectTag(status: string) {
  return TAG_MAP[status] ?? { type: 'gray', label: status };
}

// === 정산 관리 탭 ===

export const SETTLEMENT_SUMMARY = [
  { title: '누적 지원금', value: '10,000,000', description: '2000.00.00 기준', width: 'w-114.25' },
  {
    title: '지급 예정',
    value: '10,000,000',
    description: '다음 지급 예정일: 2026.07.15',
    width: 'w-84.25',
  },
  { title: '이번 달 지원금', value: '10,000,000', description: '2000.00 기준', width: 'w-84.25' },
];

export const SETTLEMENT_ROWS = [
  {
    id: '1',
    status: 'pending' as const,
    amount: '1,000,000',
    project: '제목',
    brand: '이름',
    date: '-',
  },
  {
    id: '2',
    status: 'pending' as const,
    amount: '1,000,000',
    project: '제목',
    brand: '이름',
    date: '-',
  },
  {
    id: '3',
    status: 'pending' as const,
    amount: '1,000,000',
    project: '제목',
    brand: '이름',
    date: '-',
  },
  {
    id: '4',
    status: 'pending' as const,
    amount: '1,000,000',
    project: '제목',
    brand: '이름',
    date: '-',
  },
  {
    id: '5',
    status: 'pending' as const,
    amount: '1,000,000',
    project: '제목',
    brand: '이름',
    date: '-',
  },
  {
    id: '6',
    status: 'completed' as const,
    amount: '10,000',
    project: '제목',
    brand: '이름',
    date: '2000.00.00',
  },
  {
    id: '7',
    status: 'completed' as const,
    amount: '10,000',
    project: '제목',
    brand: '이름',
    date: '2000.00.00',
  },
  {
    id: '8',
    status: 'completed' as const,
    amount: '10,000',
    project: '제목',
    brand: '이름',
    date: '2000.00.00',
  },
  {
    id: '9',
    status: 'completed' as const,
    amount: '10,000',
    project: '제목',
    brand: '이름',
    date: '2000.00.00',
  },
];

// === 빈 상태 ===

export const EMPTY_STATUS_CARDS: StatusCardData[] = STATUS_CARDS.map((c) => ({ ...c, count: 0 }));
export const EMPTY_RATINGS: CompanyRating[] = RATINGS.map((r) => ({ ...r, score: 0 }));
export const EMPTY_FUNDING = {
  amount: '0',
  message: '프로젝트를 시작하고 첫 지원금을 받아보세요!',
};

// === 프로젝트 작업 상세 ===

export const TASK_DETAIL_MOCK: TaskDetail = {
  projectTitle: '프로젝트 제목이 들어갈 자리입니다.',
  brandName: 'CONX',
  managerName: '김담당자',
  email: 'abcdefg@gmail.com',
  projectId: 'p1',
  settlementStatus: 'pending',
  settlementAmount: '500,000',
  settlementDate: '2000.00.00',
  progressSteps: [
    { label: '매칭 완료', date: '2025.05.10', type: 'completed' },
    { label: '진행 중', date: '2000.00.00', type: 'inProgress' },
    { label: '진행 완료', date: '2000.00.00 예정', type: 'notStarted' },
    { label: '제출 완료', date: '2000.00.00 예정', type: 'notStarted' },
    { label: '정산 완료', type: 'notStarted' },
  ],
  submissionCriteria: [
    { label: '숏폼 원본 파일', checked: true },
    { label: '숏폼 업로드 링크', checked: true },
    { label: '조회수/댓글 수 등 정량 지표 포함', checked: false },
    { label: '실행 회고 및 인사이트 작성', checked: false },
  ],
  results: [
    {
      id: '1',
      indicatorType: 'green',
      indicatorLabel: '답변 전',
      title: '1차 숏폼 콘텐츠 결과물 공유드립니다.',
      author: '이름',
      registeredDate: '2025.05.10',
      content:
        '안녕하세요.\n\n요청해 주신 1차 숏폼 콘텐츠 결과물을 업로드했습니다.\n\n제품의 핵심 특징이 자연스럽게 전달될 수 있도록 초반 구성과 자막 흐름을 중심으로 제작했습니다.\n\n검토 후 수정이 필요한 사항이 있다면 피드백 부탁드립니다.\n의견을 반영하여 다음 결과물에 빠르게 적용하겠습니다.\n\n감사합니다.',
      files: [
        { name: '파일명(확장자명, 용량)', description: '입력 완료 정보' },
        { name: '파일명(확장자명, 용량)' },
      ],
      links: [
        { label: '브랜드 홈페이지', url: 'https://', description: '입력 완료 정보' },
        { label: '브랜드 인스타그램 계정', url: 'https://' },
      ],
    },
    {
      id: '2',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '파일 없는 버전',
      author: '이름',
      registeredDate: '2000.00.00',
      content: '링크만 있는 결과물입니다.',
      links: [{ label: '브랜드 홈페이지', url: 'https://' }],
      feedback: {
        date: '2025.05.10',
        content:
          '안녕하세요, 제출해 주신 결과를 잘 확인했습니다.\n\n전체적으로 제품의 특징을 자연스럽게 담아낸 점이 좋았습니다. 특히 초반 3초의 화면 전환과 제품 노출 방식이 인상적이었습니다.\n\n다만 몇 가지 보완을 요청드립니다.\n\n제품 로고 노출 시간을 조금 더 확보해 주세요.\n마지막 CTA 문구의 가독성을 높여 주세요.\n자막 크기를 소폭 확대해 모바일 환경에서도 잘 보이도록 수정 부탁드립니다.\n\n수정본은 6월 20일(금)까지 업로드해 주시면 확인 후 최종 피드백을 전달드리겠습니다.',
        files: [
          { name: '파일명(확장자명, 용량)', description: '입력 완료 정보' },
          { name: '파일명(확장자명, 용량)' },
        ],
        links: [
          { label: '브랜드 홈페이지', url: 'https://', description: '입력 완료 정보' },
          { label: '브랜드 인스타그램 계정', url: 'https://' },
        ],
      },
    },
    {
      id: '3',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '링크 없는 버전',
      author: '이름',
      registeredDate: '2000.00.00',
      content: '파일만 있는 결과물입니다.',
      files: [{ name: '파일명(확장자명, 용량)', description: '입력 완료 정보' }],
    },
    {
      id: '4',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '파일과 링크 모두 없는 버전',
      author: '이름',
      registeredDate: '2000.00.00',
      content: '본문만 있는 결과물입니다.',
    },
    {
      id: '5',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
  ],
};

export const TASK_DETAIL_EMPTY_MOCK: TaskDetail = {
  projectTitle: '프로젝트 제목이 들어갈 자리입니다.',
  brandName: 'CONX',
  managerName: '김담당자',
  email: 'abcdefg@gmail.com',
  projectId: 'p2',
  settlementStatus: 'pending',
  settlementAmount: '500,000',
  progressSteps: [
    { label: '매칭 완료', date: '2025.05.10', type: 'completed' },
    { label: '진행 중', date: '2000.00.00', type: 'notStarted' },
    { label: '진행 완료', date: '2000.00.00', type: 'notStarted' },
    { label: '제출 완료', date: '2000.00.00', type: 'notStarted' },
    { label: '정산 완료', type: 'notStarted' },
  ],
  submissionCriteria: [
    { label: '숏폼 원본 파일', checked: false },
    { label: '숏폼 업로드 링크', checked: false },
    { label: '조회수/댓글 수 등 정량 지표 포함', checked: false },
    { label: '실행 회고 및 인사이트 작성', checked: false },
  ],
  results: [],
};

export const TASK_DETAIL_COMPLETED_MOCK: TaskDetail = {
  projectTitle: '프로젝트 제목이 들어갈 자리입니다.',
  brandName: 'CONX',
  managerName: '김담당자',
  email: 'abcdefg@gmail.com',
  projectId: 'p3',
  settlementStatus: 'completed',
  settlementAmount: '500,000',
  settlementDate: '2000.00.00',
  progressSteps: [
    { label: '매칭 완료', date: '2025.05.10', type: 'completed' },
    { label: '진행 중', date: '2000.00.00', type: 'completed' },
    { label: '진행 완료', date: '2000.00.00', type: 'completed' },
    { label: '제출 완료', date: '2000.00.00', type: 'completed' },
    { label: '정산 완료', date: '2000.00.00', type: 'completed' },
  ],
  submissionCriteria: [
    { label: '숏폼 원본 파일', checked: true },
    { label: '숏폼 업로드 링크', checked: true },
    { label: '조회수/댓글 수 등 정량 지표 포함', checked: true },
    { label: '실행 회고 및 인사이트 작성', checked: true },
  ],
  results: [
    {
      id: '1',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
    {
      id: '2',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
    {
      id: '3',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
    {
      id: '4',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
    {
      id: '5',
      indicatorType: 'gray',
      indicatorLabel: '답변 완료',
      title: '제목',
      author: '이름',
      registeredDate: '2000.00.00',
    },
  ],
};
